spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBUSER}
    password: ${DBPASSWORD}
    url: ${DBURL}

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
jwt:
  secret: mysecret.sjb_2023_.qwer1234.Dkagh1234! # 길어야 함
  token.expired-time-ms: 2592000000 # 30 days